// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmC5mUpXsJ3AW7ZqMymDhu_PUJee33wU',
    appId: '1:330855987877:web:640f8407c5ee617d23ab4c',
    messagingSenderId: '330855987877',
    projectId: 'count3-flutter-5959a',
    authDomain: 'count3-flutter-5959a.firebaseapp.com',
    storageBucket: 'count3-flutter-5959a.firebasestorage.app',
    measurementId: 'G-WC6EPGKP7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWARKX8da_xlF-cI227Qio2Ljbq0XAc0',
    appId: '1:330855987877:android:22e20e853c543c7723ab4c',
    messagingSenderId: '330855987877',
    projectId: 'count3-flutter-5959a',
    storageBucket: 'count3-flutter-5959a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNeTPybLwtQOYs5QmfUOEDPzDGVhxbcM4',
    appId: '1:330855987877:ios:cf5e548135533fd323ab4c',
    messagingSenderId: '330855987877',
    projectId: 'count3-flutter-5959a',
    storageBucket: 'count3-flutter-5959a.firebasestorage.app',
    androidClientId: '330855987877-q4i3udd0ohgnbgsi178hmp0i6mal0kkh.apps.googleusercontent.com',
    iosClientId: '330855987877-q8tidjku31d3q8fgbmc988tjrp2c0mtn.apps.googleusercontent.com',
    iosBundleId: 'com.example.countToThree',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNeTPybLwtQOYs5QmfUOEDPzDGVhxbcM4',
    appId: '1:330855987877:ios:cf5e548135533fd323ab4c',
    messagingSenderId: '330855987877',
    projectId: 'count3-flutter-5959a',
    storageBucket: 'count3-flutter-5959a.firebasestorage.app',
    iosBundleId: 'com.example.countToThree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmC5mUpXsJ3AW7ZqMymDhu_PUJee33wU',
    appId: '1:330855987877:web:3010af7b5311758123ab4c',
    messagingSenderId: '330855987877',
    projectId: 'count3-flutter-5959a',
    authDomain: 'count3-flutter-5959a.firebaseapp.com',
    storageBucket: 'count3-flutter-5959a.firebasestorage.app',
    measurementId: 'G-HD0YXQFF42',
  );
}
